# Generated by Django 4.1 on 2022-09-13 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastrosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('descriçao', models.CharField(max_length=150, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='CadastroMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_material', models.CharField(max_length=50, verbose_name='Nome do Material')),
                ('tipo_material', models.CharField(max_length=50, verbose_name='Tipo do Material')),
                ('descriçao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('cadastros_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.cadastrosempresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('cargo', models.CharField(max_length=20, null=True, verbose_name='Cargo')),
                ('metodo_pagamento', models.CharField(max_length=50, null=True, verbose_name='Método de Pagamento')),
                ('data_pagamento', models.CharField(max_length=50, null=True, verbose_name='Data de Pagamento')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cadastros_Funcionarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.cadastrosempresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
