# Generated by Django 4.1 on 2022-09-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrofuncionario',
            name='cadastros_Funcionarios',
        ),
        migrations.RemoveField(
            model_name='cadastromaterial',
            name='cadastros_material',
        ),
        migrations.AddField(
            model_name='cadastromaterial',
            name='data_de_hoje',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastrosempresa',
            name='setor',
            field=models.CharField(default=1, max_length=150, verbose_name='Setor'),
            preserve_default=False,
        ),
    ]
