# Generated by Django 4.1 on 2022-09-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_cadastrofuncionario_cadastros_funcionarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastromaterial',
            name='data_de_hoje',
            field=models.DateField(verbose_name='Data de Hoje'),
        ),
    ]
