# Generated by Django 4.1 on 2022-09-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_cadastromaterial_data_de_hoje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastromaterial',
            name='data_de_hoje',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Hoje'),
        ),
    ]
