# Generated by Django 4.1 on 2022-09-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_cadastromaterial_data_de_hoje'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrosempresa',
            name='documento',
            field=models.FileField(default=1, upload_to='pdf/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadastromaterial',
            name='data_de_hoje',
            field=models.DateField(verbose_name='Data do cadastro'),
        ),
    ]
