# Generated by Django 4.1 on 2022-09-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_cadastrosempresa_logo_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrosempresa',
            name='logo_cliente',
        ),
        migrations.AddField(
            model_name='cadastrosempresa',
            name='logomarca',
            field=models.ImageField(default=1, height_field=150, upload_to='img/', width_field=150),
            preserve_default=False,
        ),
    ]
