# Generated by Django 4.1 on 2022-09-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_remove_cadastrosempresa_logo_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrosempresa',
            name='logomarca',
            field=models.ImageField(height_field=150, upload_to='img/', verbose_name='Logomarca', width_field=150),
        ),
    ]
