# Generated by Django 4.1 on 2022-09-26 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0009_alter_cadastrosempresa_logomarca'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrosempresa',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadastrosempresa',
            name='logomarca',
            field=models.ImageField(upload_to='img/', verbose_name='Logomarca'),
        ),
    ]
