# Generated by Django 4.1 on 2022-10-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_alter_cadastrofuncionario_metodo_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
    ]
