# Generated by Django 4.1 on 2022-10-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_alter_cadastrofuncionario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastromaterial',
            name='data_de_hoje',
            field=models.CharField(max_length=10, null=True, verbose_name='Data do cadastro'),
        ),
    ]
