# Generated by Django 4.1 on 2022-10-24 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_cadastrosempresa_jurisdicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrosempresa',
            name='jurisdicao',
        ),
    ]
