# Generated by Django 4.1 on 2022-10-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_remove_cadastrosempresa_jurisdicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrosempresa',
            name='jurisdicao',
            field=models.CharField(choices=[('PJ', 'Pessoa Jurídica'), ('PF', 'Pessoa Física')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
