# Generated by Django 4.1 on 2022-09-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=10, verbose_name='Senha')),
            ],
        ),
    ]
