# Generated by Django 4.1 on 2022-09-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='Logomarca'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='pais',
            field=models.CharField(max_length=20, null=True, verbose_name='País'),
        ),
    ]
