# Generated by Django 4.1 on 2022-09-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfil_foto_perfil_alter_perfil_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='Foto de Perfil'),
        ),
    ]
